In [3]:
from gutenberg.acquire import load_etext
from gutenberg.cleanup import strip_headers
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
import numpy as np
import scipy.io as sio

In [4]:
 # Loads Moby Dick
mobydick = strip_headers(load_etext(2701)).strip()
text = [mobydick.split('ETYMOLOGY')[-1]]

In [5]:
# Loads Pride and Prejudice
pride = strip_headers(load_etext(1342)).strip()
text.append(pride.split('Austen')[-1])

In [6]:
# Loads Sense and Sensibility
sense = strip_headers(load_etext(161)).strip()
text.append(sense.split('\n(1811)\n\n')[-1])

In [7]:
# Loads Huck Finn
huckfinn = strip_headers(load_etext(76)).strip()
text.append(huckfinn.split('\nEXPLANATORY\n\n')[-1])

In [8]:
# Loads tom sawyer
toms = strip_headers(load_etext(74)).strip()
text.append(toms.split('\nPREFACE\n\n')[-1])

In [9]:
# Loads Twenty Thousand Leagues
leagues20k = strip_headers(load_etext(164)).strip()
text.append(leagues20k.split(' VERNE\n\n')[-1])

In [10]:
# Loads Ulysses
ulysses = strip_headers(load_etext(4300)).strip()
text.append(ulysses.split('\n— I —\n')[-1])

In [11]:
titles = ['Moby Dick','Pride and Prejudice','Huck Finn','Tom Sawyer','Sense and Sensibility','20K Leagues','Ulysses']

In [12]:
print(ulysses.split('\n— I —\n')[-1][:1000])



[ 1 ]

Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of
lather on which a mirror and a razor lay crossed. A yellow
dressinggown, ungirdled, was sustained gently behind him on the mild
morning air. He held the bowl aloft and intoned:

—_Introibo ad altare Dei_.

Halted, he peered down the dark winding stairs and called out coarsely:

—Come up, Kinch! Come up, you fearful jesuit!

Solemnly he came forward and mounted the round gunrest. He faced about
and blessed gravely thrice the tower, the surrounding land and the
awaking mountains. Then, catching sight of Stephen Dedalus, he bent
towards him and made rapid crosses in the air, gurgling in his throat
and shaking his head. Stephen Dedalus, displeased and sleepy, leaned
his arms on the top of the staircase and looked coldly at the shaking
gurgling face that blessed him, equine in its length, and at the light
untonsured hair, grained and hued like pale oak.

Buck Mulligan peeped an instant under the mirror and then

In [13]:
chapters = []
for i in range(len(text)):
    chapters.append(text[i].split('CHAPTER '))
chapters[1] = text[1].split('Chapter ') # fix
chapters[6] = text[6].split(' ]\n\n') # fix
allchaps = [y for x in chapters for y in x]

In [14]:
print(chapters[6][-1][:200])

Yes because he never did a thing like that before as ask to get his
breakfast in bed with a couple of eggs since the _City Arms_ hotel when
he used to be pretending to be laid up with a sick voice doi


In [15]:
chapix = [len(x) for x in chapters]

In [16]:
def textcounter(chapters,n_features=1000):
    tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2,
                                       max_features=n_features,
                                       stop_words='english')
    freq = tfidf_vectorizer.fit_transform(chapters)
    words = tfidf_vectorizer.get_feature_names()
    return freq, words

In [17]:
freq, words = textcounter(allchaps,50)

In [18]:
words[freq.sum(0).argmax()]

'whale'

In [19]:
sio.savemat('/Users/zaharia/books.mat',{'freq':freq.todense(),'words':np.array(words,dtype=np.object),\
                                        'chapix':chapix,'titles':np.array(titles,dtype=np.object)})

In [38]:
sepfreq = []
sepwords = []
for i in range(len(titles)):
    tmpfreq, tmpwords = textcounter(chapters[i],10)
    sepfreq.append(tmpfreq)
    sepwords.append(tmpwords)

In [39]:
sepwords

[['ahab', 'head', 'like', 'man', 'old', 'sea', 'ship', 'time', 'whale', 'ye'],
 ['bennet',
  'bingley',
  'darcy',
  'did',
  'jane',
  'know',
  'miss',
  'sister',
  'soon',
  'think'],
 ['dashwood',
  'did',
  'edward',
  'jennings',
  'know',
  'miss',
  'mother',
  'said',
  'sister',
  'willoughby'],
 ['ain', 'don', 'en', 'going', 'jim', 'like', 'll', 'man', 'old', 'tom'],
 ['boy', 'boys', 'did', 'don', 'huck', 'joe', 'just', 'little', 'll', 'said'],
 ['captain',
  'conseil',
  'land',
  'like',
  'nautilus',
  'ned',
  'nemo',
  'said',
  'sir',
  'water'],
 ['bloom',
  'did',
  'like',
  'man',
  'mr',
  'old',
  'said',
  'says',
  'stephen',
  'time']]

In [40]:
sepwords = [y for x in sepwords for y in x]
sepfreq = [y.todense() for x in sepfreq for y in x]

In [42]:
sepfreq[1:10][1:10]

[matrix([[0.        , 0.        , 0.20375414, 0.        , 0.95255841,
          0.        , 0.        , 0.12328658, 0.10895166, 0.15506992]]),
 matrix([[0.        , 0.5349729 , 0.38887602, 0.42730756, 0.40103169,
          0.19242517, 0.1155218 , 0.22145811, 0.14678136, 0.31336889]]),
 matrix([[0.        , 0.32073785, 0.49372279, 0.27125802, 0.        ,
          0.14832856, 0.        , 0.74684856, 0.        , 0.        ]]),
 matrix([[0.        , 0.15251339, 0.46953819, 0.64492668, 0.        ,
          0.56425123, 0.14820151, 0.        , 0.        , 0.        ]]),
 matrix([[0.        , 0.19036922, 0.73260471, 0.        , 0.17124776,
          0.35215292, 0.        , 0.35462476, 0.31339142, 0.2230236 ]]),
 matrix([[0.        , 0.        , 0.68589628, 0.18842037, 0.20041196,
          0.        , 0.21649115, 0.        , 0.36676328, 0.5220109 ]]),
 matrix([[0.        , 0.        , 0.26172174, 0.35948371, 0.30588979,
          0.23588626, 0.74347095, 0.31672267, 0.        , 0.        ]]),

In [41]:
sio.savemat('/Users/zaharia/books.mat',{'freq':sepfreq,'words':np.array(sepwords,dtype=np.object),\
                                        'chapix':chapix,'titles':np.array(titles,dtype=np.object)})

In [37]:
len(allchaps)

409